-- =============================================================
-- 消息中心 P0：proj_notify 表 + sys_config 参数
-- 执行库：xky_project (PostgreSQL)
-- 幂等：可重复执行（drop 不存在时忽略 / if not exists）
-- =============================================================

CREATE TABLE IF NOT EXISTS proj_notify (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notify_type      varchar(16)  NOT NULL,                 -- todo | message
    todo_kind        varchar(16),                           -- doc | settle（仅 todo）
    biz_type         varchar(32)  NOT NULL,                 -- project_closed
    biz_id           bigint       NOT NULL,                 -- 业务对象 id（项目 id）
    project_id       bigint,
    project_code     varchar(64),                           -- 冗余：列表直出
    project_name     varchar(255),                          -- 冗余：卡片副标题
    title            varchar(128) NOT NULL,
    content          varchar(512),
    receiver_id      bigint       NOT NULL,
    receiver_role_id bigint,
    route_path       varchar(128),                          -- 落地路由，如 /material
    route_query      varchar(256),                          -- projectCode=xxx&from=notify&notifyId=xx
    priority         varchar(8)   NOT NULL DEFAULT 'normal',-- normal | high
    status           varchar(12)  NOT NULL DEFAULT 'unread',-- unread | read | done | ignored
    due_time         timestamp,
    read_time        timestamp,
    done_time        timestamp,
    ignore_reason    varchar(255),
    del_flag         char(1)      NOT NULL DEFAULT '0',
    create_by        varchar(64),
    create_time      timestamp    NOT NULL DEFAULT now(),
    update_by        varchar(64),
    update_time      timestamp
);

-- 幂等物理保障：同一项目办结重复触发不产生重复通知
CREATE UNIQUE INDEX IF NOT EXISTS uk_proj_notify_biz
    ON proj_notify (biz_type, biz_id, receiver_id) WHERE del_flag = '0';

CREATE INDEX IF NOT EXISTS idx_proj_notify_receiver
    ON proj_notify (receiver_id, status, create_time DESC);

CREATE INDEX IF NOT EXISTS idx_proj_notify_type
    ON proj_notify (receiver_id, notify_type, status) WHERE del_flag = '0';

COMMENT ON TABLE proj_notify IS '站内待办与消息（按接收人一行）';

-- ---------------- sys_config 参数（可重复执行：先删后插） ----------------
DELETE FROM sys_config WHERE config_key IN (
  'notify.popup.enabled',
  'notify.popup.work.start',
  'notify.popup.work.end',
  'notify.popup.workday.only',
  'notify.popup.throttle.minutes',
  'notify.popup.duration.seconds',
  'notify.todo.due.days',
  'notify.receivers.project_closed'
);

INSERT INTO sys_config (config_name, config_key, config_value, config_type, create_by, create_time, remark) VALUES
('通知自动弹出开关',       'notify.popup.enabled',             'true',          'Y', 'admin', now(), '是否启用右上角自动弹出'),
('弹出窗口期-起点',       'notify.popup.work.start',          '08:00',         'Y', 'admin', now(), '免打扰时段起点（含）'),
('弹出窗口期-终点',       'notify.popup.work.end',            '18:00',         'Y', 'admin', now(), '免打扰时段终点（不含）'),
('周末静默',               'notify.popup.workday.only',       'true',          'Y', 'admin', now(), '周末是否不自动弹出'),
('弹出节流间隔(分钟)',     'notify.popup.throttle.minutes',   '5',             'Y', 'admin', now(), '两次自动弹出最小间隔'),
('弹出停留秒数',           'notify.popup.duration.seconds',   '8',             'Y', 'admin', now(), '卡片停留时长，高风险自动 x2'),
('待办超期天数',           'notify.todo.due.days',             '3',             'Y', 'admin', now(), '超过未处理升级为 high'),
('办结事件接收角色',       'notify.receivers.project_closed', 'role-doc,role-product,role-admin,role-qua', 'Y', 'admin', now(), '逗号分隔 role_key；前两个=待办，后两个=消息');
