-- ============================================================
-- 项目信息管理系统 — 业务表建表脚本
-- 数据库：xky_project（PostgreSQL）
-- 说明：所有业务表均预留 extra_data JSONB 列，配合 proj_field_def 实现动态字段
-- ============================================================

-- ----------------------------
-- 1、项目类别表（树形：大类→小类）
-- ----------------------------
DROP TABLE IF EXISTS proj_category;
CREATE TABLE proj_category (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id           BIGINT          DEFAULT NULL,
    name                VARCHAR(100)    DEFAULT ''      NOT NULL,
    level               INT             DEFAULT 1       NOT NULL,
    internal_price      DECIMAL(12,2)   DEFAULT NULL,
    external_price      DECIMAL(12,2)   DEFAULT NULL,
    sort_order          INT             DEFAULT 0,
    status              CHAR(1)         DEFAULT '0',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_category IS '项目类别表（树形结构）';
COMMENT ON COLUMN proj_category.parent_id IS '父级ID（NULL=大类，值=小类所属大类）';
COMMENT ON COLUMN proj_category.name IS '类别名称';
COMMENT ON COLUMN proj_category.level IS '层级（1=大类 2=小类）';
COMMENT ON COLUMN proj_category.internal_price IS '内部默认单价（小类层级有效）';
COMMENT ON COLUMN proj_category.external_price IS '外部默认单价（小类层级有效）';
COMMENT ON COLUMN proj_category.sort_order IS '排序号';
COMMENT ON COLUMN proj_category.status IS '状态（0启用 1停用）';
COMMENT ON COLUMN proj_category.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_category.remark IS '备注';

CREATE INDEX idx_proj_category_parent ON proj_category(parent_id);
CREATE INDEX idx_proj_category_level ON proj_category(level);


-- ----------------------------
-- 2、合同表
-- ----------------------------
DROP TABLE IF EXISTS proj_contract;
CREATE TABLE proj_contract (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_no         VARCHAR(50)     DEFAULT ''      NOT NULL,
    contract_name       VARCHAR(200)    DEFAULT ''      NOT NULL,
    client_unit         VARCHAR(200)    DEFAULT '',
    contact_name        VARCHAR(50)     DEFAULT '',
    contact_phone       VARCHAR(30)     DEFAULT '',
    contract_type       VARCHAR(20)     DEFAULT '',
    contract_amount     DECIMAL(12,2)   DEFAULT NULL,
    received_amount     DECIMAL(12,2)   DEFAULT NULL,
    sign_date           DATE            DEFAULT NULL,
    entrust_date        DATE            DEFAULT NULL,
    audit_date          DATE            DEFAULT NULL,
    return_date         DATE            DEFAULT NULL,
    finish_date         DATE            DEFAULT NULL,
    archive_date        DATE            DEFAULT NULL,
    archive_path        VARCHAR(500)    DEFAULT '',
    contract_period     VARCHAR(100)    DEFAULT '',
    payment_terms       TEXT            DEFAULT '',
    status             VARCHAR(20)     DEFAULT 'draft',
    is_settled          CHAR(1)         DEFAULT '0',
    extra_data          JSONB           DEFAULT '{}',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_contract IS '合同表';
COMMENT ON COLUMN proj_contract.contract_no IS '合同编号';
COMMENT ON COLUMN proj_contract.contract_name IS '合同名称';
COMMENT ON COLUMN proj_contract.client_unit IS '委托单位';
COMMENT ON COLUMN proj_contract.contact_name IS '联系人';
COMMENT ON COLUMN proj_contract.contact_phone IS '联系电话';
COMMENT ON COLUMN proj_contract.contract_type IS '合同类型（字典）';
COMMENT ON COLUMN proj_contract.contract_amount IS '合同金额';
COMMENT ON COLUMN proj_contract.received_amount IS '已到账金额';
COMMENT ON COLUMN proj_contract.sign_date IS '签署日期';
COMMENT ON COLUMN proj_contract.entrust_date IS '登记时间';
COMMENT ON COLUMN proj_contract.audit_date IS '审核日期';
COMMENT ON COLUMN proj_contract.return_date IS '用户返回日期';
COMMENT ON COLUMN proj_contract.finish_date IS '完成日期';
COMMENT ON COLUMN proj_contract.archive_date IS '归档日期';
COMMENT ON COLUMN proj_contract.archive_path IS '归档目录';
COMMENT ON COLUMN proj_contract.contract_period IS '合同期限';
COMMENT ON COLUMN proj_contract.payment_terms IS '支付条件';
COMMENT ON COLUMN proj_contract.status IS '合同状态';
COMMENT ON COLUMN proj_contract.is_settled IS '是否结算（0=未结算 1=已结算）';
COMMENT ON COLUMN proj_contract.extra_data IS '动态字段数据（JSONB）';
COMMENT ON COLUMN proj_contract.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_contract.remark IS '备注';

CREATE INDEX idx_proj_contract_no ON proj_contract(contract_no);
CREATE INDEX idx_proj_contract_extra ON proj_contract USING GIN (extra_data);


-- ----------------------------
-- 3、合同单价明细表
-- ----------------------------
DROP TABLE IF EXISTS proj_contract_price;
CREATE TABLE proj_contract_price (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_id         BIGINT          NOT NULL,
    category_id         BIGINT          NOT NULL,
    price               DECIMAL(12,2)   DEFAULT NULL,
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_contract_price IS '合同单价明细表';
COMMENT ON COLUMN proj_contract_price.contract_id IS '合同ID，关联 proj_contract.id';
COMMENT ON COLUMN proj_contract_price.category_id IS '项目类别ID（小类），关联 proj_category.id';
COMMENT ON COLUMN proj_contract_price.price IS '合同单价（不区分内/外）';

CREATE INDEX idx_proj_cp_contract ON proj_contract_price(contract_id);
CREATE INDEX idx_proj_cp_category ON proj_contract_price(category_id);
CREATE UNIQUE INDEX uk_proj_cp_contract_category ON proj_contract_price(contract_id, category_id) WHERE del_flag = '0';


-- ----------------------------
-- 4、项目主表
-- ----------------------------
DROP TABLE IF EXISTS proj_project;
CREATE TABLE proj_project (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_code            VARCHAR(50)     DEFAULT ''      NOT NULL,
    project_name            VARCHAR(200)    DEFAULT ''      NOT NULL,
    engineering_project     VARCHAR(200)    DEFAULT '',
    project_category_id     BIGINT          DEFAULT NULL,
    client_unit             VARCHAR(200)    DEFAULT '',
    contact_name            VARCHAR(50)     DEFAULT '',
    contact_phone           VARCHAR(30)     DEFAULT '',
    project_location        VARCHAR(300)    DEFAULT '',
    contract_id             BIGINT          DEFAULT NULL,
    status                  VARCHAR(20)     DEFAULT '',
    assign_date             DATE            DEFAULT NULL,
    duration_require        INTEGER         DEFAULT NULL,
    total_duration          INTEGER         DEFAULT NULL,
    extra_data              JSONB           DEFAULT '{}',
    related_project_id      BIGINT          DEFAULT NULL,
    link_rule               INTEGER         DEFAULT 0,
    close_time              TIMESTAMP       DEFAULT NULL,
    del_flag                CHAR(1)         DEFAULT '0',
    create_by               VARCHAR(64)     DEFAULT '',
    create_time             TIMESTAMP,
    update_by               VARCHAR(64)     DEFAULT '',
    update_time             TIMESTAMP,
    remark                  VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_project IS '项目主表';
COMMENT ON COLUMN proj_project.project_code IS '工程编号';
COMMENT ON COLUMN proj_project.project_name IS '项目名称';
COMMENT ON COLUMN proj_project.engineering_project IS '工程项目（自由文本，用户自行填写）';
COMMENT ON COLUMN proj_project.project_category_id IS '项目类别ID（小类），关联 proj_category.id';
COMMENT ON COLUMN proj_project.client_unit IS '委托单位';
COMMENT ON COLUMN proj_project.contact_name IS '联系人';
COMMENT ON COLUMN proj_project.contact_phone IS '联系电话';
COMMENT ON COLUMN proj_project.project_location IS '工程地点';
COMMENT ON COLUMN proj_project.contract_id IS '合同ID，关联 proj_contract.id';
COMMENT ON COLUMN proj_project.status IS '项目状态';
COMMENT ON COLUMN proj_project.extra_data IS '动态字段数据（JSONB）';
COMMENT ON COLUMN proj_project.related_project_id IS '关联定线项目ID（验线项目关联对应的定线项目）';
COMMENT ON COLUMN proj_project.close_time IS '办结时间（状态流转为 closed 时写入，报表/补验线用）';
COMMENT ON COLUMN proj_category.link_rule IS '关联规则：0=不关联，1=可选关联，2=必须关联';
COMMENT ON COLUMN proj_project.assign_date IS '安排日期（项目级）';
COMMENT ON COLUMN proj_project.duration_require IS '工期要求（天）';
COMMENT ON COLUMN proj_project.total_duration IS '总时长（天）';
COMMENT ON COLUMN proj_project.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_project.remark IS '备注';

CREATE INDEX idx_proj_project_code ON proj_project(project_code);
CREATE INDEX idx_proj_project_category ON proj_project(project_category_id);
CREATE INDEX idx_proj_project_contract ON proj_project(contract_id);
CREATE INDEX idx_proj_project_status ON proj_project(status);
CREATE INDEX idx_proj_project_assign_date ON proj_project(assign_date);
CREATE INDEX idx_proj_project_extra ON proj_project USING GIN (extra_data);


-- ----------------------------
-- 5、项目负责人关联表（多对多）
-- ----------------------------
DROP TABLE IF EXISTS proj_leader;
CREATE TABLE proj_leader (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id          BIGINT          NOT NULL,
    user_id             BIGINT          NOT NULL,
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_leader IS '项目负责人关联表';
COMMENT ON COLUMN proj_leader.project_id IS '项目ID，关联 proj_project.id';
COMMENT ON COLUMN proj_leader.user_id IS '负责人用户ID，关联 sys_user.user_id';

CREATE INDEX idx_proj_leader_project ON proj_leader(project_id);
CREATE INDEX idx_proj_leader_user ON proj_leader(user_id);
CREATE UNIQUE INDEX uk_proj_leader_project_user ON proj_leader(project_id, user_id) WHERE del_flag = '0';


-- ----------------------------
-- 6、任务表（按人拆分，独立工期）
-- ----------------------------
DROP TABLE IF EXISTS proj_task;
CREATE TABLE proj_task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id          BIGINT          NOT NULL,
    user_id             BIGINT          NOT NULL,
    task_name           VARCHAR(200)    DEFAULT ''      NOT NULL,
    assign_date         DATE            DEFAULT NULL,
    required_finish_date DATE           DEFAULT NULL,
    actual_finish_date   DATE           DEFAULT NULL,
    duration_require    VARCHAR(100)    DEFAULT '',
    total_duration      INT             DEFAULT NULL,
    status              VARCHAR(20)     DEFAULT '',
    extra_data          JSONB           DEFAULT '{}',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_task IS '任务表';
COMMENT ON COLUMN proj_task.project_id IS '项目ID，关联 proj_project.id';
COMMENT ON COLUMN proj_task.user_id IS '执行人用户ID，关联 sys_user.user_id';
COMMENT ON COLUMN proj_task.task_name IS '任务名称';
COMMENT ON COLUMN proj_task.assign_date IS '安排日期';
COMMENT ON COLUMN proj_task.required_finish_date IS '要求完成日期（计划截止）';
COMMENT ON COLUMN proj_task.actual_finish_date IS '实际完成日期';
COMMENT ON COLUMN proj_task.duration_require IS '工期要求';
COMMENT ON COLUMN proj_task.total_duration IS '总时长（天）';
COMMENT ON COLUMN proj_task.status IS '任务状态';
COMMENT ON COLUMN proj_task.extra_data IS '动态字段数据（JSONB）';
COMMENT ON COLUMN proj_task.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_task.remark IS '备注';

CREATE INDEX idx_proj_task_project ON proj_task(project_id);
CREATE INDEX idx_proj_task_user ON proj_task(user_id);
CREATE INDEX idx_proj_task_status ON proj_task(status);
CREATE INDEX idx_proj_task_extra ON proj_task USING GIN (extra_data);


-- ----------------------------
-- 7、工作量表（人 × 项目类别 录入）
-- ----------------------------
DROP TABLE IF EXISTS proj_workload;
CREATE TABLE proj_workload (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id          BIGINT          NOT NULL,
    user_id             BIGINT          NOT NULL,
    category_id         BIGINT          NOT NULL,
    internal_workload   DECIMAL(12,4)   DEFAULT 0,
    external_workload   DECIMAL(12,4)   DEFAULT 0,
    internal_price      DECIMAL(12,2)   DEFAULT NULL,
    external_price      DECIMAL(12,2)   DEFAULT NULL,
    internal_output     DECIMAL(12,2)   DEFAULT 0,
    external_output     DECIMAL(12,2)   DEFAULT 0,
    workload            DECIMAL(12,4)   DEFAULT 0,
    price_source        VARCHAR(20)     DEFAULT 'dict',
    billing_type        VARCHAR(20)     DEFAULT '',
    billing_category    VARCHAR(100)     DEFAULT '',
    price_unit          VARCHAR(50)     DEFAULT '',
    min_quantity        DECIMAL(12,4),
    unit_price          DECIMAL(12,2),
    extra_data          JSONB           DEFAULT '{}',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_workload IS '工作量表';
COMMENT ON COLUMN proj_workload.project_id IS '项目ID，关联 proj_project.id';
COMMENT ON COLUMN proj_workload.user_id IS '执行人用户ID，关联 sys_user.user_id';
COMMENT ON COLUMN proj_workload.category_id IS '项目类别ID（小类），关联 proj_category.id';
COMMENT ON COLUMN proj_workload.internal_workload IS '内部工作量';
COMMENT ON COLUMN proj_workload.external_workload IS '外部工作量';
COMMENT ON COLUMN proj_workload.internal_price IS '采用的内部单价';
COMMENT ON COLUMN proj_workload.external_price IS '采用的外部单价';
COMMENT ON COLUMN proj_workload.internal_output IS '内部产值（工作量×内部单价，自动计算）';
COMMENT ON COLUMN proj_workload.external_output IS '外部产值（工作量×外部单价，自动计算）';
COMMENT ON COLUMN proj_workload.workload IS '工作量（统一字段）';
COMMENT ON COLUMN proj_workload.price_source IS '单价来源（contract=合同价 dict=字典默认价 manual=手动覆盖）';
COMMENT ON COLUMN proj_workload.billing_type IS '计费类型（internal=内部 external=外部）';
COMMENT ON COLUMN proj_workload.billing_category IS '计费类别（如：常规、加急）';
COMMENT ON COLUMN proj_workload.price_unit IS '计价单位（如：平方公里、公里）';
COMMENT ON COLUMN proj_workload.min_quantity IS '起步量（最低计价数量，不足按起步量计算）';
COMMENT ON COLUMN proj_workload.unit_price IS '采用的单价（元）';
COMMENT ON COLUMN proj_workload.extra_data IS '动态字段数据（JSONB）';
COMMENT ON COLUMN proj_workload.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_workload.remark IS '备注';

CREATE INDEX idx_proj_workload_project ON proj_workload(project_id);
CREATE INDEX idx_proj_workload_user ON proj_workload(user_id);
CREATE INDEX idx_proj_workload_category ON proj_workload(category_id);
CREATE INDEX idx_proj_workload_extra ON proj_workload USING GIN (extra_data);
CREATE UNIQUE INDEX IF NOT EXISTS idx_workload_unique ON proj_workload (project_id, user_id, category_id) WHERE del_flag = '0';
CREATE UNIQUE INDEX IF NOT EXISTS idx_payment_unique ON proj_payment (project_id, payment_type) WHERE del_flag = '0' AND payment_type <> 'refund';
CREATE UNIQUE INDEX IF NOT EXISTS uk_workload_billing ON proj_workload (project_id, user_id, category_id, billing_type, billing_category) WHERE del_flag = '0';


-- ----------------------------
-- 8、付款记录表
-- ----------------------------
DROP TABLE IF EXISTS proj_payment;
CREATE TABLE proj_payment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id          BIGINT          NOT NULL,
    payment_type        VARCHAR(20)     DEFAULT ''      NOT NULL,
    amount              DECIMAL(12,2)   DEFAULT 0,
    pay_time            DATE            DEFAULT NULL,
    pay_unit            VARCHAR(200)    DEFAULT '',
    pay_method          VARCHAR(100)    DEFAULT '',
    invoice_no          VARCHAR(100)    DEFAULT '',
    invoice_date        DATE            DEFAULT NULL,
    invoice_amount      DECIMAL(12,2)   DEFAULT 0,
    invoice_status      VARCHAR(20)     DEFAULT '',
    received_status     VARCHAR(20)     DEFAULT 'pending',
    extra_data          JSONB           DEFAULT '{}',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_payment IS '付款记录表';
COMMENT ON COLUMN proj_payment.project_id IS '项目ID，关联 proj_project.id';
COMMENT ON COLUMN proj_payment.payment_type IS '付款类型（预付款/尾款/进度款/退款）';
COMMENT ON COLUMN proj_payment.amount IS '金额';
COMMENT ON COLUMN proj_payment.pay_time IS '付款时间';
COMMENT ON COLUMN proj_payment.pay_unit IS '付款单位';
COMMENT ON COLUMN proj_payment.pay_method IS '付款方式';
COMMENT ON COLUMN proj_payment.invoice_no IS '发票号';
COMMENT ON COLUMN proj_payment.invoice_date IS '发票日期';
COMMENT ON COLUMN proj_payment.invoice_amount IS '发票金额';
COMMENT ON COLUMN proj_payment.invoice_status IS '发票状态';
COMMENT ON COLUMN proj_payment.received_status IS '到账状态（字典 proj_payment_received_status）';
COMMENT ON COLUMN proj_payment.extra_data IS '动态字段数据（JSONB）';
COMMENT ON COLUMN proj_payment.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_payment.remark IS '备注';

CREATE INDEX idx_proj_payment_project ON proj_payment(project_id);
CREATE INDEX idx_proj_payment_type ON proj_payment(payment_type);
CREATE INDEX idx_proj_payment_extra ON proj_payment USING GIN (extra_data);


-- ----------------------------
-- 9、资料提交表
-- ----------------------------
DROP TABLE IF EXISTS proj_material;
CREATE TABLE proj_material (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id          BIGINT          NOT NULL,
    submit_time         TIMESTAMP       DEFAULT NULL,
    contact_name        VARCHAR(50)     DEFAULT '',
    contact_phone       VARCHAR(30)     DEFAULT '',
    result_type         VARCHAR(50)     DEFAULT '',
    archive_dir         VARCHAR(500)    DEFAULT '',
    archive_flag        CHAR(1)         DEFAULT 'N',
    archive_time       TIMESTAMP       DEFAULT NULL,
    status              VARCHAR(20)     DEFAULT '',
    submit_status       VARCHAR(20)     DEFAULT 'pending',
    guarantor_flag      CHAR(1)         DEFAULT 'N',
    guarantor_id        BIGINT          DEFAULT NULL,
    extra_data          JSONB           DEFAULT '{}',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_material IS '资料提交表';
COMMENT ON COLUMN proj_material.project_id IS '项目ID，关联 proj_project.id';
COMMENT ON COLUMN proj_material.submit_time IS '提交时间';
COMMENT ON COLUMN proj_material.contact_name IS '联系人';
COMMENT ON COLUMN proj_material.contact_phone IS '联系电话';
COMMENT ON COLUMN proj_material.result_type IS '成果类型（字典 proj_material_result_type）';
COMMENT ON COLUMN proj_material.archive_dir IS '目录';
COMMENT ON COLUMN proj_material.archive_flag IS '是否档案室归档（Y已归档 N未归档）';
COMMENT ON COLUMN proj_material.archive_time IS '归档时间';
COMMENT ON COLUMN proj_material.status IS '资料流转状态（字典 proj_material_status）';
COMMENT ON COLUMN proj_material.submit_status IS '提交状态（字典 proj_material_submit_status）';
COMMENT ON COLUMN proj_material.guarantor_flag IS '是否担保（Y需要 N不需要）';
COMMENT ON COLUMN proj_material.guarantor_id IS '担保人ID（关联sys_user.user_id）';
COMMENT ON COLUMN proj_material.extra_data IS '动态字段数据（JSONB）';
COMMENT ON COLUMN proj_material.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_material.remark IS '备注';

CREATE INDEX idx_proj_material_project ON proj_material(project_id);
CREATE INDEX idx_proj_material_extra ON proj_material USING GIN (extra_data);
CREATE INDEX idx_proj_material_guarantor ON proj_material(guarantor_id);

-- 资料流转记录表r
DROP TABLE IF EXISTS proj_material_flow;
CREATE TABLE proj_material_flow (r
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    material_id BIGINT NOT NULL, flow_type VARCHAR(20) NOT NULL,
    user_id BIGINT, guarantor_id BIGINT,
    operate_time TIMESTAMP DEFAULT now(),
    remark VARCHAR(500), del_flag VARCHAR(2) DEFAULT '0',
    create_time TIMESTAMP DEFAULT now()
);
COMMENT ON COLUMN proj_material_flow.id            IS '主键';
COMMENT ON COLUMN proj_material_flow.material_id   IS '资料ID（关联proj_material.id）';
COMMENT ON COLUMN proj_material_flow.flow_type     IS '操作类型（领取/归还）';
COMMENT ON COLUMN proj_material_flow.user_id       IS '操作人ID（关联sys_user.user_id）';
COMMENT ON COLUMN proj_material_flow.guarantor_id  IS '担保人ID（首次领取时必填，关联sys_user.user_id）';
COMMENT ON COLUMN proj_material_flow.operate_time  IS '操作时间';
COMMENT ON COLUMN proj_material_flow.remark        IS '备注';
COMMENT ON COLUMN proj_material_flow.del_flag      IS '删除标志（0=正常，2=删除）';
COMMENT ON COLUMN proj_material_flow.create_time   IS '创建时间';

-- ----------------------------
-- 10、动态字段定义表
-- ----------------------------
DROP TABLE IF EXISTS proj_field_def;
CREATE TABLE proj_field_def (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_name          VARCHAR(50)     DEFAULT ''      NOT NULL,
    field_key           VARCHAR(50)     DEFAULT ''      NOT NULL,
    field_label         VARCHAR(100)    DEFAULT ''      NOT NULL,
    field_type          VARCHAR(20)     DEFAULT 'text'  NOT NULL,
    field_options       TEXT            DEFAULT NULL,
    is_required         CHAR(1)         DEFAULT '0',
    sort_order          INT             DEFAULT 0,
    status              CHAR(1)         DEFAULT '0',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_field_def IS '动态字段定义表';
COMMENT ON COLUMN proj_field_def.table_name IS '目标表名（proj_project / proj_contract / proj_task / proj_workload / proj_payment / proj_material）';
COMMENT ON COLUMN proj_field_def.field_key IS '字段标识（对应 extra_data JSONB 中的 key）';
COMMENT ON COLUMN proj_field_def.field_label IS '字段显示名称';
COMMENT ON COLUMN proj_field_def.field_type IS '字段类型（text=文本 number=数字 date=日期 select=下拉 datetime=日期时间 textarea=多行文本）';
COMMENT ON COLUMN proj_field_def.field_options IS '选项列表（select 类型时使用，JSON 数组格式）';
COMMENT ON COLUMN proj_field_def.is_required IS '是否必填（0否 1是）';
COMMENT ON COLUMN proj_field_def.sort_order IS '排序号';
COMMENT ON COLUMN proj_field_def.status IS '状态（0启用 1停用）';
COMMENT ON COLUMN proj_field_def.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_field_def.remark IS '备注';

CREATE INDEX idx_proj_fd_table ON proj_field_def(table_name);
CREATE UNIQUE INDEX uk_proj_fd_table_key ON proj_field_def(table_name, field_key) WHERE del_flag = '0';


-- ----------------------------
-- 11、预警规则表
-- ----------------------------
DROP TABLE IF EXISTS proj_alert_rule;
CREATE TABLE proj_alert_rule (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rule_name           VARCHAR(100)    DEFAULT ''      NOT NULL,
    target_table        VARCHAR(50)     DEFAULT ''      NOT NULL,
    trigger_condition   VARCHAR(200)    DEFAULT ''      NOT NULL,
    check_sql           TEXT            DEFAULT '',
    alert_type          VARCHAR(20)     DEFAULT 'notice' NOT NULL,
    alert_receivers     VARCHAR(500)    DEFAULT '',
    cron_expression     VARCHAR(100)    DEFAULT '',
    status              CHAR(1)         DEFAULT '0',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_alert_rule IS '预警规则表';
COMMENT ON COLUMN proj_alert_rule.rule_name IS '规则名称';
COMMENT ON COLUMN proj_alert_rule.target_table IS '目标表';
COMMENT ON COLUMN proj_alert_rule.trigger_condition IS '触发条件描述';
COMMENT ON COLUMN proj_alert_rule.check_sql IS '检查 SQL';
COMMENT ON COLUMN proj_alert_rule.alert_type IS '预警类型（notice=站内通知）';
COMMENT ON COLUMN proj_alert_rule.alert_receivers IS '通知接收人（用户ID列表，逗号分隔）';
COMMENT ON COLUMN proj_alert_rule.cron_expression IS '扫描 cron 表达式';
COMMENT ON COLUMN proj_alert_rule.status IS '状态（0启用 1停用）';
COMMENT ON COLUMN proj_alert_rule.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_alert_rule.remark IS '备注';


-- ----------------------------
-- 12、预警日志表
-- ----------------------------
DROP TABLE IF EXISTS proj_alert_log;
CREATE TABLE proj_alert_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rule_id             BIGINT          NOT NULL,
    triggered_at        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    alert_content       TEXT            DEFAULT '',
    is_read             CHAR(1)         DEFAULT '0',
    read_by             BIGINT          DEFAULT NULL,
    read_at             TIMESTAMP       DEFAULT NULL,
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_alert_log IS '预警日志表';
COMMENT ON COLUMN proj_alert_log.rule_id IS '预警规则ID，关联 proj_alert_rule.id';
COMMENT ON COLUMN proj_alert_log.triggered_at IS '触发时间';
COMMENT ON COLUMN proj_alert_log.alert_content IS '预警内容';
COMMENT ON COLUMN proj_alert_log.is_read IS '是否已读（0未读 1已读）';
COMMENT ON COLUMN proj_alert_log.read_by IS '阅读人用户ID';
COMMENT ON COLUMN proj_alert_log.read_at IS '阅读时间';

CREATE INDEX idx_proj_alert_log_rule ON proj_alert_log(rule_id);
CREATE INDEX idx_proj_alert_log_read ON proj_alert_log(is_read);


-- ============================================================
-- 汇总
-- ============================================================
-- 表数量：12 张
-- 含 extra_data JSONB 的业务表（6 张）：proj_project, proj_contract, proj_task, proj_workload, proj_payment, proj_material
-- GIN 索引：6 个（对应 6 张 extra_data 表）
-- 配置/中间表（6 张）：proj_category, proj_contract_price, proj_leader, proj_field_def, proj_alert_rule, proj_alert_log
-- ============================================================

-- ============================================================
-- 角色字段权限配置表
-- 说明：按角色 + 表 + 字段 三个维度控制字段的可见/可编辑性
-- 权限类型：1=可见可编辑  2=可见不可编辑  3=隐藏
-- 注意：不在此表中的字段默认视为"可见可编辑"
-- ============================================================

DROP TABLE IF EXISTS sys_role_field_auth;
CREATE TABLE sys_role_field_auth (
 id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 role_id         BIGINT          NOT NULL,
 table_name      VARCHAR(50)     DEFAULT ''      NOT NULL,
 field_key       VARCHAR(50)     DEFAULT ''      NOT NULL,
 auth_type       CHAR(1)         DEFAULT '1'     NOT NULL,
 PRIMARY KEY (id)
);

COMMENT ON TABLE sys_role_field_auth IS '角色字段权限配置表';
COMMENT ON COLUMN sys_role_field_auth.role_id IS '角色ID，关联 sys_role.role_id';
COMMENT ON COLUMN sys_role_field_auth.table_name IS '目标表名（proj_project / proj_contract / proj_task / proj_workload / proj_payment / proj_material / proj_category）';
COMMENT ON COLUMN sys_role_field_auth.field_key IS '字段标识（固定字段=列名，动态字段=extra_data 中的 JSON key，特殊值 * 代表该表所有字段）';
COMMENT ON COLUMN sys_role_field_auth.auth_type IS '权限类型（1=可见可编辑  2=可见不可编辑  3=隐藏）';

CREATE UNIQUE INDEX uk_role_table_field ON sys_role_field_auth(role_id, table_name, field_key);
CREATE INDEX idx_role_field_auth_role ON sys_role_field_auth(role_id);
CREATE INDEX idx_role_field_auth_table ON sys_role_field_auth(table_name);

-- ----------------------------
-- 8、合同附件表（当前活跃文件）
-- ----------------------------
DROP TABLE IF EXISTS proj_contract_attachment;
CREATE TABLE proj_contract_attachment (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  contract_id         BIGINT          NOT NULL,
  file_name           VARCHAR(200)    DEFAULT ''      NOT NULL,
  file_path           VARCHAR(500)    DEFAULT ''      NOT NULL,
  file_size           BIGINT          DEFAULT 0,
  file_type           VARCHAR(20)     DEFAULT '',
  file_category       VARCHAR(30)     DEFAULT 'other' NOT NULL,
  is_final            CHAR(1)         DEFAULT '0',
  version             INT             DEFAULT 1       NOT NULL,
  sort_order          INT             DEFAULT 0,
  del_flag            CHAR(1)         DEFAULT '0',
  create_by           VARCHAR(64)     DEFAULT '',
  create_time         TIMESTAMP,
  update_by           VARCHAR(64)     DEFAULT '',
  update_time         TIMESTAMP,
  remark              VARCHAR(500)    DEFAULT NULL,
  PRIMARY KEY (id)
);

COMMENT ON TABLE proj_contract_attachment IS '合同附件表（当前活跃文件）';
COMMENT ON COLUMN proj_contract_attachment.contract_id IS '关联合同ID';
COMMENT ON COLUMN proj_contract_attachment.file_name IS '原始文件名';
COMMENT ON COLUMN proj_contract_attachment.file_path IS '服务端存储路径';
COMMENT ON COLUMN proj_contract_attachment.file_size IS '文件大小（字节）';
COMMENT ON COLUMN proj_contract_attachment.file_type IS '文件扩展名（pdf/jpg/png/doc/docx/xlsx等）';
COMMENT ON COLUMN proj_contract_attachment.file_category IS '文件归类（contract=合同正本 supplement=补充协议 acceptance=验收单 invoice=票据 other=其他）';
COMMENT ON COLUMN proj_contract_attachment.is_final IS '是否签章/盖章版（1=是 0=否）';
COMMENT ON COLUMN proj_contract_attachment.version IS '当前版本号';
COMMENT ON COLUMN proj_contract_attachment.sort_order IS '排序号';
COMMENT ON COLUMN proj_contract_attachment.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_contract_attachment.remark IS '备注';

CREATE INDEX idx_att_contract ON proj_contract_attachment(contract_id, del_flag);
CREATE INDEX idx_att_category ON proj_contract_attachment(contract_id, file_category);


-- ----------------------------
-- 9、合同附件版本历史表
-- ----------------------------
DROP TABLE IF EXISTS proj_contract_attachment_log;
CREATE TABLE proj_contract_attachment_log (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  attachment_id       BIGINT          NOT NULL,
  contract_id         BIGINT          NOT NULL,
  file_name           VARCHAR(200)    DEFAULT '',
  file_path           VARCHAR(500)    DEFAULT '',
  file_size           BIGINT          DEFAULT 0,
  file_type           VARCHAR(20)     DEFAULT '',
  file_category       VARCHAR(30)     DEFAULT 'other',
  is_final            CHAR(1)         DEFAULT '0',
  version             INT             NOT NULL,
  action              VARCHAR(20)     NOT NULL,
  operator            VARCHAR(64)     DEFAULT '',
  operate_time        TIMESTAMP,
  remark              VARCHAR(500)    DEFAULT NULL,
  PRIMARY KEY (id)
);

COMMENT ON TABLE proj_contract_attachment_log IS '合同附件版本历史表';
COMMENT ON COLUMN proj_contract_attachment_log.attachment_id IS '关联附件槽位ID';
COMMENT ON COLUMN proj_contract_attachment_log.contract_id IS '关联合同ID（冗余，方便直接按合同查历史）';
COMMENT ON COLUMN proj_contract_attachment_log.file_name IS '该版本的原始文件名';
COMMENT ON COLUMN proj_contract_attachment_log.file_path IS '该版本的文件路径';
COMMENT ON COLUMN proj_contract_attachment_log.file_size IS '文件大小（字节）';
COMMENT ON COLUMN proj_contract_attachment_log.file_type IS '文件扩展名';
COMMENT ON COLUMN proj_contract_attachment_log.file_category IS '文件归类';
COMMENT ON COLUMN proj_contract_attachment_log.is_final IS '是否签章/盖章版';
COMMENT ON COLUMN proj_contract_attachment_log.version IS '版本号';
COMMENT ON COLUMN proj_contract_attachment_log.action IS '操作类型（upload/replace/delete/restore）';
COMMENT ON COLUMN proj_contract_attachment_log.operator IS '操作人';
COMMENT ON COLUMN proj_contract_attachment_log.operate_time IS '操作时间';
COMMENT ON COLUMN proj_contract_attachment_log.remark IS '操作备注';

CREATE INDEX idx_attlog_attachment ON proj_contract_attachment_log(attachment_id);
CREATE INDEX idx_attlog_contract ON proj_contract_attachment_log(contract_id);

-- ----------------------------
-- 1、工作日历表
-- ----------------------------
DROP TABLE IF EXISTS proj_workday_calendar;
CREATE TABLE proj_workday_calendar (
    day                 DATE            NOT NULL,
    day_type            VARCHAR(10)     DEFAULT 'weekend' NOT NULL,
    remark              VARCHAR(200)    DEFAULT '',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    PRIMARY KEY (day)
);

COMMENT ON TABLE proj_workday_calendar IS '工作日历表（每天一条，记录节假日/调休上班日及周末基线）';
COMMENT ON COLUMN proj_workday_calendar.day IS '日期（主键）';
COMMENT ON COLUMN proj_workday_calendar.day_type IS '日类型（holiday=法定节假日休息 workday=调休上班日 weekend=周末休息基线）';
COMMENT ON COLUMN proj_workday_calendar.remark IS '备注（如：春节假期、国庆调休等）';

CREATE INDEX idx_proj_wd_type ON proj_workday_calendar(day_type);

-- ----------------------------
-- 2、2026 年内置数据（国务院办公厅《关于2026年部分节假日安排的通知》）
--    共 33 天休息 + 6 天调休上班
-- ----------------------------

-- 2.1 法定节假日休息（33 天）
INSERT INTO proj_workday_calendar (day, day_type, remark, create_by, create_time) VALUES
  ('2026-01-01', 'holiday', '元旦', 'admin', now()),
  ('2026-01-02', 'holiday', '元旦', 'admin', now()),
  ('2026-01-03', 'holiday', '元旦', 'admin', now()),
  ('2026-02-15', 'holiday', '春节', 'admin', now()),
  ('2026-02-16', 'holiday', '春节', 'admin', now()),
  ('2026-02-17', 'holiday', '春节', 'admin', now()),
  ('2026-02-18', 'holiday', '春节', 'admin', now()),
  ('2026-02-19', 'holiday', '春节', 'admin', now()),
  ('2026-02-20', 'holiday', '春节', 'admin', now()),
  ('2026-02-21', 'holiday', '春节', 'admin', now()),
  ('2026-02-22', 'holiday', '春节', 'admin', now()),
  ('2026-02-23', 'holiday', '春节', 'admin', now()),
  ('2026-04-04', 'holiday', '清明节', 'admin', now()),
  ('2026-04-05', 'holiday', '清明节', 'admin', now()),
  ('2026-04-06', 'holiday', '清明节', 'admin', now()),
  ('2026-05-01', 'holiday', '劳动节', 'admin', now()),
  ('2026-05-02', 'holiday', '劳动节', 'admin', now()),
  ('2026-05-03', 'holiday', '劳动节', 'admin', now()),
  ('2026-05-04', 'holiday', '劳动节', 'admin', now()),
  ('2026-05-05', 'holiday', '劳动节', 'admin', now()),
  ('2026-06-19', 'holiday', '端午节', 'admin', now()),
  ('2026-06-20', 'holiday', '端午节', 'admin', now()),
  ('2026-06-21', 'holiday', '端午节', 'admin', now()),
  ('2026-09-25', 'holiday', '中秋节', 'admin', now()),
  ('2026-09-26', 'holiday', '中秋节', 'admin', now()),
  ('2026-09-27', 'holiday', '中秋节', 'admin', now()),
  ('2026-10-01', 'holiday', '国庆节', 'admin', now()),
  ('2026-10-02', 'holiday', '国庆节', 'admin', now()),
  ('2026-10-03', 'holiday', '国庆节', 'admin', now()),
  ('2026-10-04', 'holiday', '国庆节', 'admin', now()),
  ('2026-10-05', 'holiday', '国庆节', 'admin', now()),
  ('2026-10-06', 'holiday', '国庆节', 'admin', now()),
  ('2026-10-07', 'holiday', '国庆节', 'admin', now());

-- 2.2 调休上班日（6 天，均为周末）
INSERT INTO proj_workday_calendar (day, day_type, remark, create_by, create_time) VALUES
  ('2026-01-04', 'workday', '元旦调休上班', 'admin', now()),
  ('2026-02-14', 'workday', '春节调休上班', 'admin', now()),
  ('2026-02-28', 'workday', '春节调休上班', 'admin', now()),
  ('2026-05-09', 'workday', '劳动节调休上班', 'admin', now()),
  ('2026-09-20', 'workday', '国庆调休上班', 'admin', now()),
  ('2026-10-10', 'workday', '国庆调休上班', 'admin', now());

-- 2.3 2026 年周末基线（全年周六/周日，ON CONFLICT 幂等，可重复执行）
INSERT INTO proj_workday_calendar (day, day_type, remark, create_by, create_time)
SELECT d::date, 'weekend', '周末基线（自动生成）', 'admin', now()
FROM generate_series('2026-01-01'::date, '2026-12-31'::date, '1 day') AS d
WHERE EXTRACT(ISODOW FROM d) IN (6, 7)
    ON CONFLICT (day) DO NOTHING;

-- -----------------------------------------------
-- 1. 报表模板表（内置 / 自定义）
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS proj_report_template (
                                                    id                BIGSERIAL PRIMARY KEY,
                                                    template_name     VARCHAR(100) NOT NULL,             -- 模板名称
    template_type     VARCHAR(20)  DEFAULT 'custom',     -- builtin 内置 / custom 自定义
    subject_table     VARCHAR(50)  DEFAULT 'proj_project', -- 数据主体（proj_project / proj_task / proj_workload / proj_payment / proj_material / proj_contract）
    source_template_id BIGINT,                            -- 自定义模板的来源内置模板 ID（内置模板为 NULL）
    template_file     VARCHAR(255),                       -- 内置模板文件（classpath:reportTemplates/xxx.xls 或绝对路径）
    file_name         VARCHAR(255),                       -- 原始文件名
    title_row         INT          DEFAULT 1,             -- 标题行号（1-based，0 表示无标题）
    header_row        INT          DEFAULT 2,             -- 表头行号（1-based）
    data_start_row    INT          DEFAULT 3,             -- 数据起始行（1-based）
    has_summary_row   CHAR(1)      DEFAULT 'N',           -- 导出是否追加合计行（Y/N）
    default_filter    JSONB,                              -- 模板默认筛选条件（JSONB）
    remark            VARCHAR(500),
    del_flag          CHAR(1)      DEFAULT '0',           -- 0正常 2删除
    create_by         VARCHAR(64)  DEFAULT '',
    create_time       TIMESTAMP    DEFAULT now(),
    update_by         VARCHAR(64)  DEFAULT '',
    update_time       TIMESTAMP    DEFAULT now()
    );
COMMENT ON TABLE proj_report_template IS '报表导出-模板表';

-- -----------------------------------------------
-- 2. 模板字段表（内置模板列映射 / 自定义模板勾选字段）
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS proj_report_field (
                                                 id                BIGSERIAL PRIMARY KEY,
                                                 template_id       BIGINT NOT NULL,                   -- 所属模板 ID
                                                 field_key         VARCHAR(100) NOT NULL,             -- 字段键（如 project.client_unit / agg.receivedAmount / dynamic.xxx）
    field_label       VARCHAR(100),                      -- 列名（表头显示名）
    field_source      VARCHAR(20)  DEFAULT 'subject',    -- subject 主体 / join 关联带出 / agg 聚合计算 / dynamic 动态字段
    join_table        VARCHAR(50),                       -- 关联表（join 类型使用）
    sort_order        INT          DEFAULT 0,            -- 排序
    width             INT          DEFAULT 120,          -- 列宽（字符数）
    column_index      INT,                               -- 内置模板中对应列序号（1-based，仅内置模板使用）
    del_flag          CHAR(1)      DEFAULT '0'
    );
CREATE INDEX IF NOT EXISTS idx_report_field_tpl ON proj_report_field(template_id);
COMMENT ON TABLE proj_report_field IS '报表导出-模板字段表';

-- -----------------------------------------------
-- 3. 筛选方案表（用户自定义筛选器勾选 + 值）
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS proj_report_filter (
                                                  id                BIGSERIAL PRIMARY KEY,
                                                  filter_name       VARCHAR(100) NOT NULL,             -- 方案名称
    filter_config     JSONB NOT NULL,                    -- {selected:[字段key...], values:{key:value}}
    create_by         VARCHAR(64)  DEFAULT '',
    create_time       TIMESTAMP    DEFAULT now(),
    update_by         VARCHAR(64)  DEFAULT '',
    update_time       TIMESTAMP    DEFAULT now(),
    del_flag          CHAR(1)      DEFAULT '0'
    );
COMMENT ON TABLE proj_report_filter IS '报表导出-筛选方案表';

-- -----------------------------------------------
-- 4. 导出历史表（谁/何时/哪个模板/什么筛选/多少行）
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS proj_report_log (
                                               id                BIGSERIAL PRIMARY KEY,
                                               template_id       BIGINT,                            -- 使用的模板 ID
                                               template_name     VARCHAR(100),                      -- 模板名称快照
    filter_name       VARCHAR(100),                      -- 筛选方案名称快照
    filter_config     JSONB,                             -- 筛选条件快照
    row_count         INT          DEFAULT 0,            -- 导出行数
    export_by         VARCHAR(64)  DEFAULT '',           -- 操作人
    export_time       TIMESTAMP    DEFAULT now(),        -- 导出时间
    file_name         VARCHAR(255)                       -- 导出文件名
    );
COMMENT ON TABLE proj_report_log IS '报表导出-导出历史表';

-- =============================================================
-- 项目类别计费方式表
-- 每个小类可配置多条内部/外部计费方式（计费类别、单价、计价单位、起步量）
-- 执行时间：2026-08
-- =============================================================

CREATE TABLE proj_category_billing (
   id               BIGSERIAL PRIMARY KEY,
   category_id      BIGINT        NOT NULL,                -- 关联 proj_category.id（小类）
   billing_type     VARCHAR(10)   NOT NULL,                -- 计费类型：internal=内部 external=外部
   billing_category VARCHAR(100)  NOT NULL,                -- 计费类别（如：常规测绘、加急测绘）
   unit_price       DECIMAL(12,2) NOT NULL,                -- 单价（元）
   price_unit       VARCHAR(50)   NOT NULL,                -- 计价单位（如：平方公里、公里、宗）
   min_quantity     DECIMAL(12,4) DEFAULT 1,               -- 起步量（不足按起步量计算）
   sort_order       INT           DEFAULT 0,               -- 排序
   status           CHAR(1)       DEFAULT '0',             -- 状态（0启用 1停用）
   del_flag         CHAR(1)       DEFAULT '0',             -- 删除标志（0正常 2删除）
   create_by        VARCHAR(64)   DEFAULT '',
   create_time      TIMESTAMP,
   update_by        VARCHAR(64)   DEFAULT '',
   update_time      TIMESTAMP,
   CONSTRAINT fk_pcb_category FOREIGN KEY (category_id) REFERENCES proj_category (id)
);

COMMENT ON TABLE  proj_category_billing             IS '项目类别计费方式表';
COMMENT ON COLUMN proj_category_billing.category_id      IS '类别ID（小类）';
COMMENT ON COLUMN proj_category_billing.billing_type     IS '计费类型（internal=内部 external=外部）';
COMMENT ON COLUMN proj_category_billing.billing_category IS '计费类别（如：常规测绘、加急测绘）';
COMMENT ON COLUMN proj_category_billing.unit_price       IS '单价（元）';
COMMENT ON COLUMN proj_category_billing.price_unit       IS '计价单位（如：平方公里、公里、宗）';
COMMENT ON COLUMN proj_category_billing.min_quantity     IS '起步量（最低计价数量，不足按起步量计算）';

CREATE INDEX idx_pcb_category ON proj_category_billing (category_id);

-- -----------------------------------------------
-- 报表上报：批次表 + 记录表（新库轨道；线上库增量见 14 号脚本，幂等可重复执行）
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS proj_report_submit_batch (
    id            BIGSERIAL PRIMARY KEY,
    batch_no      VARCHAR(32) NOT NULL,       -- 批次号：SB+yyyyMMdd+3位序号
    template_id   BIGINT NOT NULL,            -- 上报所用模板（当前=1 zdyw）
    submit_time   TIMESTAMP NOT NULL,         -- 批次上报时间
    submit_by     VARCHAR(64) NOT NULL,       -- 操作人
    project_count INT NOT NULL,               -- 本次上报工程条数
    filter_desc   VARCHAR(500),               -- 本次筛选范围描述
    snapshot_file VARCHAR(255),               -- 上报快照文件（服务器路径）
    remark        VARCHAR(500),               -- 备注
    create_time   TIMESTAMP DEFAULT now(),
    del_flag      CHAR(1) DEFAULT '0'
);
COMMENT ON TABLE proj_report_submit_batch IS '报表上报批次表（一次导出上报 = 一个批次，记录筛选范围 + 快照路径）';

CREATE TABLE IF NOT EXISTS proj_report_submit_log (
    id            BIGSERIAL PRIMARY KEY,
    project_code  VARCHAR(64) NOT NULL,       -- 工程编号（zdyw 报表系统编号）
    project_name  VARCHAR(255),               -- 冗余，便于展示
    unit_name     VARCHAR(255),               -- 单位名称（冗余）
    submit_time   TIMESTAMP NOT NULL,         -- 真实上报领导时间（now()）
    submit_by     VARCHAR(64) NOT NULL,       -- 操作人
    batch_id      BIGINT,                     -- 所属批次
    create_time   TIMESTAMP DEFAULT now(),
    del_flag      CHAR(1) DEFAULT '0'
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_submit_log_code ON proj_report_submit_log(project_code);
CREATE INDEX IF NOT EXISTS idx_submit_log_time ON proj_report_submit_log(submit_time);
COMMENT ON TABLE proj_report_submit_log IS '报表上报记录表（每条工程编号一行，project_code 唯一索引锁定上报时间——上报后不可再更新）';

-- 上报批次表（一次导出上报 = 一个批次，记录筛选范围 + 快照路径）
CREATE TABLE IF NOT EXISTS proj_report_submit_batch (
    id            BIGSERIAL PRIMARY KEY,
    batch_no      VARCHAR(32) NOT NULL,       -- 批次号：SB+yyyyMMdd+3位序号
    template_id   BIGINT NOT NULL,            -- 上报所用模板（当前=1 zdyw）
    submit_time   TIMESTAMP NOT NULL,         -- 批次上报时间
    submit_by     VARCHAR(64) NOT NULL,       -- 操作人
    project_count INT NOT NULL,               -- 本次上报工程条数
    filter_desc   VARCHAR(500),               -- 本次筛选范围描述
    snapshot_file VARCHAR(255),               -- 上报快照文件（服务器路径）
    remark        VARCHAR(500),               -- 备注
    create_time   TIMESTAMP DEFAULT now(),
    del_flag      CHAR(1) DEFAULT '0'
    );

-- 3. 上报记录表（每条工程编号一行，UNIQUE 锁定上报时间——上报后不可再更新）
CREATE TABLE IF NOT EXISTS proj_report_submit_log (
    id            BIGSERIAL PRIMARY KEY,
    project_code  VARCHAR(64) NOT NULL,       -- 工程编号（zdyw 报表系统编号）
    project_name  VARCHAR(255),               -- 冗余，便于展示
    unit_name     VARCHAR(255),               -- 单位名称（冗余）
    submit_time   TIMESTAMP NOT NULL,         -- 真实上报领导时间（now()）
    submit_by     VARCHAR(64) NOT NULL,       -- 操作人
    batch_id      BIGINT,                     -- 所属批次
    create_time   TIMESTAMP DEFAULT now(),
    del_flag      CHAR(1) DEFAULT '0'
    );
CREATE UNIQUE INDEX IF NOT EXISTS uk_submit_log_code ON proj_report_submit_log(project_code);
CREATE INDEX IF NOT EXISTS idx_submit_log_time ON proj_report_submit_log(submit_time);

-- -----------------------------------------------
-- 1. 催收记录表 proj_collection_log
--    回款管理页面的催收闭环：每次催收登记一条，
--    next_collect_time 到期未再催 → 前端标红"超期未催"
-- -----------------------------------------------
create table if not exists proj_collection_log (
    id                  bigserial       primary key,
    project_id          bigint          not null,               -- 关联 proj_project.id
    collect_time        date            not null,               -- 催收时间
    collect_method      varchar(20),                            -- 催收方式（电话/函件/上门）
    contact_name        varchar(50),                            -- 联系人
    collect_result      varchar(200),                           -- 催收结果
    next_collect_time   date,                                   -- 下次催收日期（超期未催预警依据）
    remark              varchar(500),
    del_flag            char(1)         default '0' not null,
    create_by           varchar(64),
    create_time         timestamp       default now(),
    update_by           varchar(64),
    update_time         timestamp
    );

comment on table proj_collection_log is '回款催收记录表';
comment on column proj_collection_log.project_id is '项目ID，关联 proj_project.id';
comment on column proj_collection_log.collect_time is '催收时间';
comment on column proj_collection_log.collect_method is '催收方式（电话/函件/上门）';
comment on column proj_collection_log.contact_name is '联系人';
comment on column proj_collection_log.collect_result is '催收结果';
comment on column proj_collection_log.next_collect_time is '下次催收日期，超期未催预警依据';
comment on column proj_collection_log.remark is '备注';

create index if not exists idx_pcl_project on proj_collection_log(project_id);