-- ============================================================
-- 项目信息管理系统 — 业务表建表脚本
-- 数据库：xky_project（PostgreSQL）
-- 说明：所有业务表均预留 extra_data JSONB 列，配合 proj_field_def 实现动态字段
-- ============================================================

-- ----------------------------
-- 1、项目类别表（树形：大类→小类）
-- ----------------------------
DROP TABLE IF EXISTS proj_category;
CREATE TABLE proj_category (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id           BIGINT          DEFAULT NULL,
    name                VARCHAR(100)    DEFAULT ''      NOT NULL,
    level               INT             DEFAULT 1       NOT NULL,
    internal_price      DECIMAL(12,2)   DEFAULT NULL,
    external_price      DECIMAL(12,2)   DEFAULT NULL,
    sort_order          INT             DEFAULT 0,
    status              CHAR(1)         DEFAULT '0',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_category IS '项目类别表（树形结构）';
COMMENT ON COLUMN proj_category.parent_id IS '父级ID（NULL=大类，值=小类所属大类）';
COMMENT ON COLUMN proj_category.name IS '类别名称';
COMMENT ON COLUMN proj_category.level IS '层级（1=大类 2=小类）';
COMMENT ON COLUMN proj_category.internal_price IS '内部默认单价（小类层级有效）';
COMMENT ON COLUMN proj_category.external_price IS '外部默认单价（小类层级有效）';
COMMENT ON COLUMN proj_category.sort_order IS '排序号';
COMMENT ON COLUMN proj_category.status IS '状态（0启用 1停用）';
COMMENT ON COLUMN proj_category.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_category.remark IS '备注';

CREATE INDEX idx_proj_category_parent ON proj_category(parent_id);
CREATE INDEX idx_proj_category_level ON proj_category(level);


-- ----------------------------
-- 2、合同表
-- ----------------------------
DROP TABLE IF EXISTS proj_contract;
CREATE TABLE proj_contract (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_no         VARCHAR(50)     DEFAULT ''      NOT NULL,
    contract_name       VARCHAR(200)    DEFAULT ''      NOT NULL,
    client_unit         VARCHAR(200)    DEFAULT '',
    contact_name        VARCHAR(50)     DEFAULT '',
    contact_phone       VARCHAR(30)     DEFAULT '',
    contract_type       VARCHAR(20)     DEFAULT '',
    contract_amount     DECIMAL(12,2)   DEFAULT NULL,
    sign_date           DATE            DEFAULT NULL,
    entrust_date        DATE            DEFAULT NULL,
    audit_date          DATE            DEFAULT NULL,
    return_date         DATE            DEFAULT NULL,
    finish_date         DATE            DEFAULT NULL,
    archive_date        DATE            DEFAULT NULL,
    archive_path        VARCHAR(500)    DEFAULT '',
    contract_period     VARCHAR(100)    DEFAULT '',
    payment_terms       TEXT            DEFAULT '',
    extra_data          JSONB           DEFAULT '{}',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_contract IS '合同表';
COMMENT ON COLUMN proj_contract.contract_no IS '合同编号';
COMMENT ON COLUMN proj_contract.contract_name IS '合同名称';
COMMENT ON COLUMN proj_contract.client_unit IS '委托单位';
COMMENT ON COLUMN proj_contract.contact_name IS '联系人';
COMMENT ON COLUMN proj_contract.contact_phone IS '联系电话';
COMMENT ON COLUMN proj_contract.contract_type IS '合同类型（字典）';
COMMENT ON COLUMN proj_contract.contract_amount IS '合同金额';
COMMENT ON COLUMN proj_contract.sign_date IS '签署日期';
COMMENT ON COLUMN proj_contract.entrust_date IS '委托时间';
COMMENT ON COLUMN proj_contract.audit_date IS '审核日期';
COMMENT ON COLUMN proj_contract.return_date IS '用户返回日期';
COMMENT ON COLUMN proj_contract.finish_date IS '完成日期';
COMMENT ON COLUMN proj_contract.archive_date IS '归档日期';
COMMENT ON COLUMN proj_contract.archive_path IS '归档目录';
COMMENT ON COLUMN proj_contract.contract_period IS '合同期限';
COMMENT ON COLUMN proj_contract.payment_terms IS '支付条件';
COMMENT ON COLUMN proj_contract.extra_data IS '动态字段数据（JSONB）';
COMMENT ON COLUMN proj_contract.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_contract.remark IS '备注';

CREATE INDEX idx_proj_contract_no ON proj_contract(contract_no);
CREATE INDEX idx_proj_contract_extra ON proj_contract USING GIN (extra_data);


-- ----------------------------
-- 3、合同单价明细表
-- ----------------------------
DROP TABLE IF EXISTS proj_contract_price;
CREATE TABLE proj_contract_price (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_id         BIGINT          NOT NULL,
    category_id         BIGINT          NOT NULL,
    internal_price      DECIMAL(12,2)   DEFAULT NULL,
    external_price      DECIMAL(12,2)   DEFAULT NULL,
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_contract_price IS '合同单价明细表';
COMMENT ON COLUMN proj_contract_price.contract_id IS '合同ID，关联 proj_contract.id';
COMMENT ON COLUMN proj_contract_price.category_id IS '项目类别ID（小类），关联 proj_category.id';
COMMENT ON COLUMN proj_contract_price.internal_price IS '内部单价（合同约定）';
COMMENT ON COLUMN proj_contract_price.external_price IS '外部单价（合同约定）';

CREATE INDEX idx_proj_cp_contract ON proj_contract_price(contract_id);
CREATE INDEX idx_proj_cp_category ON proj_contract_price(category_id);
CREATE UNIQUE INDEX uk_proj_cp_contract_category ON proj_contract_price(contract_id, category_id) WHERE del_flag = '0';


-- ----------------------------
-- 4、项目主表
-- ----------------------------
DROP TABLE IF EXISTS proj_project;
CREATE TABLE proj_project (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_code            VARCHAR(50)     DEFAULT ''      NOT NULL,
    project_name            VARCHAR(200)    DEFAULT ''      NOT NULL,
    engineering_project     VARCHAR(200)    DEFAULT '',
    project_category_id     BIGINT          DEFAULT NULL,
    client_unit             VARCHAR(200)    DEFAULT '',
    contact_name            VARCHAR(50)     DEFAULT '',
    contact_phone           VARCHAR(30)     DEFAULT '',
    project_location        VARCHAR(300)    DEFAULT '',
    contract_id             BIGINT          DEFAULT NULL,
    status                  VARCHAR(20)     DEFAULT '',
    extra_data              JSONB           DEFAULT '{}',
    del_flag                CHAR(1)         DEFAULT '0',
    create_by               VARCHAR(64)     DEFAULT '',
    create_time             TIMESTAMP,
    update_by               VARCHAR(64)     DEFAULT '',
    update_time             TIMESTAMP,
    remark                  VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_project IS '项目主表';
COMMENT ON COLUMN proj_project.project_code IS '工程编号';
COMMENT ON COLUMN proj_project.project_name IS '项目名称';
COMMENT ON COLUMN proj_project.engineering_project IS '工程项目（自由文本，用户自行填写）';
COMMENT ON COLUMN proj_project.project_category_id IS '项目类别ID（小类），关联 proj_category.id';
COMMENT ON COLUMN proj_project.client_unit IS '委托单位';
COMMENT ON COLUMN proj_project.contact_name IS '联系人';
COMMENT ON COLUMN proj_project.contact_phone IS '联系电话';
COMMENT ON COLUMN proj_project.project_location IS '工程地点';
COMMENT ON COLUMN proj_project.contract_id IS '合同ID，关联 proj_contract.id';
COMMENT ON COLUMN proj_project.status IS '项目状态';
COMMENT ON COLUMN proj_project.extra_data IS '动态字段数据（JSONB）';
COMMENT ON COLUMN proj_project.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_project.remark IS '备注';

CREATE INDEX idx_proj_project_code ON proj_project(project_code);
CREATE INDEX idx_proj_project_category ON proj_project(project_category_id);
CREATE INDEX idx_proj_project_contract ON proj_project(contract_id);
CREATE INDEX idx_proj_project_status ON proj_project(status);
CREATE INDEX idx_proj_project_extra ON proj_project USING GIN (extra_data);


-- ----------------------------
-- 5、项目负责人关联表（多对多）
-- ----------------------------
DROP TABLE IF EXISTS proj_leader;
CREATE TABLE proj_leader (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id          BIGINT          NOT NULL,
    user_id             BIGINT          NOT NULL,
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_leader IS '项目负责人关联表';
COMMENT ON COLUMN proj_leader.project_id IS '项目ID，关联 proj_project.id';
COMMENT ON COLUMN proj_leader.user_id IS '负责人用户ID，关联 sys_user.user_id';

CREATE INDEX idx_proj_leader_project ON proj_leader(project_id);
CREATE INDEX idx_proj_leader_user ON proj_leader(user_id);
CREATE UNIQUE INDEX uk_proj_leader_project_user ON proj_leader(project_id, user_id) WHERE del_flag = '0';


-- ----------------------------
-- 6、任务表（按人拆分，独立工期）
-- ----------------------------
DROP TABLE IF EXISTS proj_task;
CREATE TABLE proj_task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id          BIGINT          NOT NULL,
    user_id             BIGINT          NOT NULL,
    task_name           VARCHAR(200)    DEFAULT ''      NOT NULL,
    assign_date         DATE            DEFAULT NULL,
    finish_date         DATE            DEFAULT NULL,
    duration_require    VARCHAR(100)    DEFAULT '',
    total_duration      INT             DEFAULT NULL,
    status              VARCHAR(20)     DEFAULT '',
    extra_data          JSONB           DEFAULT '{}',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_task IS '任务表';
COMMENT ON COLUMN proj_task.project_id IS '项目ID，关联 proj_project.id';
COMMENT ON COLUMN proj_task.user_id IS '执行人用户ID，关联 sys_user.user_id';
COMMENT ON COLUMN proj_task.task_name IS '任务名称';
COMMENT ON COLUMN proj_task.assign_date IS '安排日期';
COMMENT ON COLUMN proj_task.finish_date IS '完成日期';
COMMENT ON COLUMN proj_task.duration_require IS '工期要求';
COMMENT ON COLUMN proj_task.total_duration IS '总时长（天）';
COMMENT ON COLUMN proj_task.status IS '任务状态';
COMMENT ON COLUMN proj_task.extra_data IS '动态字段数据（JSONB）';
COMMENT ON COLUMN proj_task.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_task.remark IS '备注';

CREATE INDEX idx_proj_task_project ON proj_task(project_id);
CREATE INDEX idx_proj_task_user ON proj_task(user_id);
CREATE INDEX idx_proj_task_status ON proj_task(status);
CREATE INDEX idx_proj_task_extra ON proj_task USING GIN (extra_data);


-- ----------------------------
-- 7、工作量表（人 × 项目类别 录入）
-- ----------------------------
DROP TABLE IF EXISTS proj_workload;
CREATE TABLE proj_workload (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id          BIGINT          NOT NULL,
    user_id             BIGINT          NOT NULL,
    category_id         BIGINT          NOT NULL,
    internal_workload   DECIMAL(12,4)   DEFAULT 0,
    external_workload   DECIMAL(12,4)   DEFAULT 0,
    internal_price      DECIMAL(12,2)   DEFAULT NULL,
    external_price      DECIMAL(12,2)   DEFAULT NULL,
    internal_output     DECIMAL(12,2)   DEFAULT 0,
    external_output     DECIMAL(12,2)   DEFAULT 0,
    price_source        VARCHAR(20)     DEFAULT 'dict',
    extra_data          JSONB           DEFAULT '{}',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_workload IS '工作量表';
COMMENT ON COLUMN proj_workload.project_id IS '项目ID，关联 proj_project.id';
COMMENT ON COLUMN proj_workload.user_id IS '执行人用户ID，关联 sys_user.user_id';
COMMENT ON COLUMN proj_workload.category_id IS '项目类别ID（小类），关联 proj_category.id';
COMMENT ON COLUMN proj_workload.internal_workload IS '内部工作量';
COMMENT ON COLUMN proj_workload.external_workload IS '外部工作量';
COMMENT ON COLUMN proj_workload.internal_price IS '采用的内部单价';
COMMENT ON COLUMN proj_workload.external_price IS '采用的外部单价';
COMMENT ON COLUMN proj_workload.internal_output IS '内部产值（工作量×内部单价，自动计算）';
COMMENT ON COLUMN proj_workload.external_output IS '外部产值（工作量×外部单价，自动计算）';
COMMENT ON COLUMN proj_workload.price_source IS '单价来源（contract=合同价 dict=字典默认价 manual=手动覆盖）';
COMMENT ON COLUMN proj_workload.extra_data IS '动态字段数据（JSONB）';
COMMENT ON COLUMN proj_workload.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_workload.remark IS '备注';

CREATE INDEX idx_proj_workload_project ON proj_workload(project_id);
CREATE INDEX idx_proj_workload_user ON proj_workload(user_id);
CREATE INDEX idx_proj_workload_category ON proj_workload(category_id);
CREATE INDEX idx_proj_workload_extra ON proj_workload USING GIN (extra_data);


-- ----------------------------
-- 8、付款记录表
-- ----------------------------
DROP TABLE IF EXISTS proj_payment;
CREATE TABLE proj_payment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id          BIGINT          NOT NULL,
    payment_type        VARCHAR(20)     DEFAULT ''      NOT NULL,
    amount              DECIMAL(12,2)   DEFAULT 0,
    pay_time            DATE            DEFAULT NULL,
    pay_unit            VARCHAR(200)    DEFAULT '',
    pay_method          VARCHAR(100)    DEFAULT '',
    extra_data          JSONB           DEFAULT '{}',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_payment IS '付款记录表';
COMMENT ON COLUMN proj_payment.project_id IS '项目ID，关联 proj_project.id';
COMMENT ON COLUMN proj_payment.payment_type IS '付款类型（预付款/尾款/进度款）';
COMMENT ON COLUMN proj_payment.amount IS '金额';
COMMENT ON COLUMN proj_payment.pay_time IS '付款时间';
COMMENT ON COLUMN proj_payment.pay_unit IS '付款单位';
COMMENT ON COLUMN proj_payment.pay_method IS '付款方式';
COMMENT ON COLUMN proj_payment.extra_data IS '动态字段数据（JSONB）';
COMMENT ON COLUMN proj_payment.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_payment.remark IS '备注';

CREATE INDEX idx_proj_payment_project ON proj_payment(project_id);
CREATE INDEX idx_proj_payment_type ON proj_payment(payment_type);
CREATE INDEX idx_proj_payment_extra ON proj_payment USING GIN (extra_data);


-- ----------------------------
-- 9、资料提交表
-- ----------------------------
DROP TABLE IF EXISTS proj_material;
CREATE TABLE proj_material (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id          BIGINT          NOT NULL,
    submit_time         TIMESTAMP       DEFAULT NULL,
    contact_name        VARCHAR(50)     DEFAULT '',
    contact_phone       VARCHAR(30)     DEFAULT '',
    result_type         VARCHAR(50)     DEFAULT '',
    extra_data          JSONB           DEFAULT '{}',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_material IS '资料提交表';
COMMENT ON COLUMN proj_material.project_id IS '项目ID，关联 proj_project.id';
COMMENT ON COLUMN proj_material.submit_time IS '提交时间';
COMMENT ON COLUMN proj_material.contact_name IS '联系人';
COMMENT ON COLUMN proj_material.contact_phone IS '联系电话';
COMMENT ON COLUMN proj_material.result_type IS '成果类型';
COMMENT ON COLUMN proj_material.extra_data IS '动态字段数据（JSONB）';
COMMENT ON COLUMN proj_material.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_material.remark IS '备注';

CREATE INDEX idx_proj_material_project ON proj_material(project_id);
CREATE INDEX idx_proj_material_extra ON proj_material USING GIN (extra_data);


-- ----------------------------
-- 10、动态字段定义表
-- ----------------------------
DROP TABLE IF EXISTS proj_field_def;
CREATE TABLE proj_field_def (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_name          VARCHAR(50)     DEFAULT ''      NOT NULL,
    field_key           VARCHAR(50)     DEFAULT ''      NOT NULL,
    field_label         VARCHAR(100)    DEFAULT ''      NOT NULL,
    field_type          VARCHAR(20)     DEFAULT 'text'  NOT NULL,
    field_options       TEXT            DEFAULT NULL,
    is_required         CHAR(1)         DEFAULT '0',
    sort_order          INT             DEFAULT 0,
    status              CHAR(1)         DEFAULT '0',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_field_def IS '动态字段定义表';
COMMENT ON COLUMN proj_field_def.table_name IS '目标表名（proj_project / proj_contract / proj_task / proj_workload / proj_payment / proj_material）';
COMMENT ON COLUMN proj_field_def.field_key IS '字段标识（对应 extra_data JSONB 中的 key）';
COMMENT ON COLUMN proj_field_def.field_label IS '字段显示名称';
COMMENT ON COLUMN proj_field_def.field_type IS '字段类型（text=文本 number=数字 date=日期 select=下拉 datetime=日期时间 textarea=多行文本）';
COMMENT ON COLUMN proj_field_def.field_options IS '选项列表（select 类型时使用，JSON 数组格式）';
COMMENT ON COLUMN proj_field_def.is_required IS '是否必填（0否 1是）';
COMMENT ON COLUMN proj_field_def.sort_order IS '排序号';
COMMENT ON COLUMN proj_field_def.status IS '状态（0启用 1停用）';
COMMENT ON COLUMN proj_field_def.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_field_def.remark IS '备注';

CREATE INDEX idx_proj_fd_table ON proj_field_def(table_name);
CREATE UNIQUE INDEX uk_proj_fd_table_key ON proj_field_def(table_name, field_key) WHERE del_flag = '0';


-- ----------------------------
-- 11、预警规则表
-- ----------------------------
DROP TABLE IF EXISTS proj_alert_rule;
CREATE TABLE proj_alert_rule (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rule_name           VARCHAR(100)    DEFAULT ''      NOT NULL,
    target_table        VARCHAR(50)     DEFAULT ''      NOT NULL,
    trigger_condition   VARCHAR(200)    DEFAULT ''      NOT NULL,
    check_sql           TEXT            DEFAULT '',
    alert_type          VARCHAR(20)     DEFAULT 'notice' NOT NULL,
    alert_receivers     VARCHAR(500)    DEFAULT '',
    cron_expression     VARCHAR(100)    DEFAULT '',
    status              CHAR(1)         DEFAULT '0',
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    remark              VARCHAR(500)    DEFAULT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_alert_rule IS '预警规则表';
COMMENT ON COLUMN proj_alert_rule.rule_name IS '规则名称';
COMMENT ON COLUMN proj_alert_rule.target_table IS '目标表';
COMMENT ON COLUMN proj_alert_rule.trigger_condition IS '触发条件描述';
COMMENT ON COLUMN proj_alert_rule.check_sql IS '检查 SQL';
COMMENT ON COLUMN proj_alert_rule.alert_type IS '预警类型（notice=站内通知）';
COMMENT ON COLUMN proj_alert_rule.alert_receivers IS '通知接收人（用户ID列表，逗号分隔）';
COMMENT ON COLUMN proj_alert_rule.cron_expression IS '扫描 cron 表达式';
COMMENT ON COLUMN proj_alert_rule.status IS '状态（0启用 1停用）';
COMMENT ON COLUMN proj_alert_rule.del_flag IS '删除标志（0正常 2删除）';
COMMENT ON COLUMN proj_alert_rule.remark IS '备注';


-- ----------------------------
-- 12、预警日志表
-- ----------------------------
DROP TABLE IF EXISTS proj_alert_log;
CREATE TABLE proj_alert_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rule_id             BIGINT          NOT NULL,
    triggered_at        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    alert_content       TEXT            DEFAULT '',
    is_read             CHAR(1)         DEFAULT '0',
    read_by             BIGINT          DEFAULT NULL,
    read_at             TIMESTAMP       DEFAULT NULL,
    del_flag            CHAR(1)         DEFAULT '0',
    create_by           VARCHAR(64)     DEFAULT '',
    create_time         TIMESTAMP,
    update_by           VARCHAR(64)     DEFAULT '',
    update_time         TIMESTAMP,
    PRIMARY KEY (id)
);

COMMENT ON TABLE proj_alert_log IS '预警日志表';
COMMENT ON COLUMN proj_alert_log.rule_id IS '预警规则ID，关联 proj_alert_rule.id';
COMMENT ON COLUMN proj_alert_log.triggered_at IS '触发时间';
COMMENT ON COLUMN proj_alert_log.alert_content IS '预警内容';
COMMENT ON COLUMN proj_alert_log.is_read IS '是否已读（0未读 1已读）';
COMMENT ON COLUMN proj_alert_log.read_by IS '阅读人用户ID';
COMMENT ON COLUMN proj_alert_log.read_at IS '阅读时间';

CREATE INDEX idx_proj_alert_log_rule ON proj_alert_log(rule_id);
CREATE INDEX idx_proj_alert_log_read ON proj_alert_log(is_read);


-- ============================================================
-- 汇总
-- ============================================================
-- 表数量：12 张
-- 含 extra_data JSONB 的业务表（6 张）：proj_project, proj_contract, proj_task, proj_workload, proj_payment, proj_material
-- GIN 索引：6 个（对应 6 张 extra_data 表）
-- 配置/中间表（6 张）：proj_category, proj_contract_price, proj_leader, proj_field_def, proj_alert_rule, proj_alert_log
-- ============================================================
