-- ============================================================
-- 角色字段权限配置表
-- 说明：按角色 + 表 + 字段 三个维度控制字段的可见/可编辑性
-- 权限类型：1=可见可编辑  2=可见不可编辑  3=隐藏
-- 注意：不在此表中的字段默认视为"可见可编辑"
-- ============================================================

DROP TABLE IF EXISTS sys_role_field_auth;
CREATE TABLE sys_role_field_auth (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id         BIGINT          NOT NULL,
    table_name      VARCHAR(50)     DEFAULT ''      NOT NULL,
    field_key       VARCHAR(50)     DEFAULT ''      NOT NULL,
    auth_type       CHAR(1)         DEFAULT '1'     NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE sys_role_field_auth IS '角色字段权限配置表';
COMMENT ON COLUMN sys_role_field_auth.role_id IS '角色ID，关联 sys_role.role_id';
COMMENT ON COLUMN sys_role_field_auth.table_name IS '目标表名（proj_project / proj_contract / proj_task / proj_workload / proj_payment / proj_material / proj_category）';
COMMENT ON COLUMN sys_role_field_auth.field_key IS '字段标识（固定字段=列名，动态字段=extra_data 中的 JSON key，特殊值 * 代表该表所有字段）';
COMMENT ON COLUMN sys_role_field_auth.auth_type IS '权限类型（1=可见可编辑  2=可见不可编辑  3=隐藏）';

CREATE UNIQUE INDEX uk_role_table_field ON sys_role_field_auth(role_id, table_name, field_key);
CREATE INDEX idx_role_field_auth_role ON sys_role_field_auth(role_id);
CREATE INDEX idx_role_field_auth_table ON sys_role_field_auth(table_name);


-- ============================================================
-- 字段权限菜单 + 按钮权限
-- 在系统管理 → 角色管理页面中增加"字段权限"配置入口
-- ============================================================

-- 直接在角色管理的菜单下增加按钮权限标识即可（无需新增菜单，因为字段权限是角色管理的一个Tab/弹窗）
-- 如果有菜单表，在角色管理的菜单记录中增加 perms 字段即可
-- 此处提供 SQL 示例，实际菜单 ID 需根据数据库中的值调整

-- 为角色管理菜单增加"字段权限"按钮权限（假设角色管理菜单的 perms 字段需要扩展）
-- 实际执行方式：在系统管理界面手动给角色管理菜单添加权限字符，或在菜单初始化脚本中追加

-- 如果需要独立的字段权限管理菜单（不在角色管理内嵌），可以执行以下 INSERT
-- INSERT INTO sys_menu (menu_name, parent_id, order_num, path, component, menu_type, visible, status, perms, icon, create_by, create_time)
-- VALUES ('字段权限', 1, 6, 'filedauth', 'system/fieldauth/index', 'C', '0', '0', 'system:fieldauth:list', 'lock', 'admin', now());
